// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdPFuCWK6FrZh_Bm_kfJR3lD231nGh0GI',
    appId: '1:643916253041:web:883330793ae9c58ea398d0',
    messagingSenderId: '643916253041',
    projectId: 'smart-training-13143',
    authDomain: 'smart-training-13143.firebaseapp.com',
    storageBucket: 'smart-training-13143.appspot.com',
    measurementId: 'G-VM6CTD32MV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmmzh28xnR-tMEx8yrsYzL15a5gKt6uyI',
    appId: '1:643916253041:android:7c7a21ea058ecffda398d0',
    messagingSenderId: '643916253041',
    projectId: 'smart-training-13143',
    storageBucket: 'smart-training-13143.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTvgwexeg55qf8CQGz_l6AP5rgCqfiOj8',
    appId: '1:643916253041:ios:1077400752f8a359a398d0',
    messagingSenderId: '643916253041',
    projectId: 'smart-training-13143',
    storageBucket: 'smart-training-13143.appspot.com',
    iosBundleId: 'com.example.smartTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTvgwexeg55qf8CQGz_l6AP5rgCqfiOj8',
    appId: '1:643916253041:ios:993989fe8dee988ea398d0',
    messagingSenderId: '643916253041',
    projectId: 'smart-training-13143',
    storageBucket: 'smart-training-13143.appspot.com',
    iosBundleId: 'com.example.smartTraining.RunnerTests',
  );
}
